### PR TITLE
Improved performance, support for Gifs and support for pose models

### PR DESCRIPTION
**Pull request by acowusu**
Switching from @tensorflow/tfjs to @tensorflow/tfjs-node makes inference around **7** times faster as @tensorflow/tfjs-node uses the TensorFlow C binary

Using `tf.node.decodeImage` rather than `tf.browser.fromPixels` in conjunction with `PImage.decodePNGFromStream`/`PImage.decodeJPEGFromStream`  makes it possible to use gifs 

Added dependency @tensorflow-models/posenet to allow for inference on posenet models

### CODE REVIEW

**Comment by IraGR** [comment]
@penguinprogramer Thanks for wanting to contribute to SashiDo's teachablemachine-node. Unfortunately, we're unable to test the improvements you've made because the installations of some packages fail with the following errors. 

**For Node.Js 12.22.1:**
```
ERROR {
  error: Error: Invalid TF_Status: 3
  Message: Input to reshape is a tensor with 100352 values, but the requested shape has 150528

```
With **Node.Js 10.2.1** it's completely impossible to install the changes due to the following error:
```
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v3/3.8.0/CPU-darwin-3.8.0.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@3.8.0 and node@10.2.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v3/3.8.0/CPU-darwin-3.8.0.tar.gz
../binding/tfjs_backend.cc:426:26: error: use of undeclared identifier 'napi_bigint64_array'
      typed_array_type = napi_bigint64_array;
                         ^
1 error generated.
make: *** [Release/obj.target/tfjs_binding/binding/tfjs_backend.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

**Comment by acowusu** [comment]
In regards to the first error, would you be able to provide some sample code and an accompanying image so that i can reproduce it?

This is the code I have been using  to test the pose model and it seems to work with nodejs **v12.22.1** and **v14.17.1**
```js
const TeachableMachine = require("./index.js");

const model = new TeachableMachine({
    modelUrl: "https://teachablemachine.withgoogle.com/models/aH894BqRS/"
});

model.classify({
    imageUrl: "https://i.ibb.co/Xxtf0WY/thumb-3-0083.jpg",
}).then((predictions) => {
    console.log("Predictions:", predictions);5
}).catch((e) => {
    console.log("ERROR", e);
});

```
And image models still work two using the sample code from README.md
```js
const TeachableMachine = require("./index.js");

const model = new TeachableMachine({
  modelUrl: "https://teachablemachine.withgoogle.com/models/r6BBk-hiN/"
});

model.classify({
  imageUrl: "https://media-blog.sashido.io/content/images/2020/09/SashiDo_Dog.jpg",
}).then((predictions) => {
  console.log("Predictions:", predictions);
}).catch((e) => {
  console.log("ERROR", e);
});
```


As for the second error, I think this is caused during the installation of `tfjs-node` with `node-gyp`. One remedy could be to switch to using the `tfjs` dependency however since **v10.2.1** has reached [End-of-Life](https://github.com/nodejs/Release#release-phases) and this worsens performance significantly, I am not sure whether that is a good idea.

**Comment by IraGR** [comment]
@penguinprogramer  We've run some additional tests installing the changes implemented and with the following example.

```
const TeachableMachine = require("@sashido/teachablemachine-node");

const model = new TeachableMachine({
  modelUrl: "https://teachablemachine.withgoogle.com/models/aH894BqRS/"
});

model.classify({
  imageUrl: "https://i.ibb.co/Xxtf0WY/thumb-3-0083.jpg",
}).then((predictions) => {
  console.log("Predictions:", predictions); 5
}).catch((e) => {
  console.log("ERROR", e);
});
```
After running the above-mentioned example, we get the following error:

```
2021-10-01 09:59:30.261259: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
ERROR {
  error: TypeError: Cannot read property 'inputResolution' of undefined
      at estimatePoseOutputs (@sashido/teachablemachine-node/index.js:97:40)
      at estimatePose (@sashido/teachablemachine-node/index.js:115:13)
      at predictPose (@sashido/teachablemachine-node/index.js:58:61)
      at @sashido/teachablemachine-node/index.js:223:79
      at Array.map (<anonymous>)
      at SashiDoTeachableMachine.inference (@sashido/teachablemachine-node/index.js:223:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
}
```

The issue seems to be related to some incompatibility of macOS and some of the newly installed packages. As you can imagine, while the above-mentioned error is still present, it will be not possible to approve the PR. Still, if you could offer a working alternative, our team would gladly release a new 2.0.0 version of the package with the awesome development work you did.
